{{- if and .Values.ingress.enabled (include "stargate.ingress.useIngress" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stargate-stack
  labels:
    app.kubernetes.io/name: stargate-stack
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    stargate.macroadster.io/ingress-provider: {{ include "stargate.ingress.provider" . }}
  {{- with include "stargate.ingress.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "stargate.ingress.className" . }}
  rules:
  {{- if .Values.ingress.frontendHost }}
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stargate
                port:
                  number: {{ .Values.stargate.port | default 3001 }}
  {{- end }}
  {{- if .Values.ingress.backendHost }}
    - host: {{ .Values.ingress.backendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stargate
                port:
                  number: {{ .Values.stargate.port | default 3001 }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
