apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-backend
spec:
  selector:
    matchLabels:
      app: stargate-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: stargate-backend
    spec:
      containers:
        - name: stargate
          image: "{{ .Values.image.stargate.repository }}:{{ .Values.image.stargate.tag }}"
          imagePullPolicy: {{ .Values.image.stargate.pullPolicy }}
          env:
            - name: STARGATE_STORAGE
              value: {{ .Values.stargate.storage | quote }}
            - name: STARGATE_PG_DSN
              value: {{ .Values.stargate.pgDsn | quote }}
            - name: STARGATE_PROXY_BASE
              value: {{ .Values.stargate.proxyBase | quote }}
            - name: BITCOIN_NETWORK
              value: {{ .Values.stargate.bitcoinNetwork | quote }}
            - name: BLOCKS_DIR
              value: /data/blocks
            - name: STARGATE_INGEST_TOKEN
              {{- if and .Values.secrets.name (or .Values.secrets.createDefault .Values.secrets.stargateIngestToken) }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: stargate-ingest-token
                  optional: true
              {{- else }}
              value: {{ .Values.stargate.ingestToken | quote }}
              {{- end }}
            - name: STARGATE_API_KEY
              {{- if and .Values.secrets.name (or .Values.secrets.createDefault .Values.secrets.stargateApiKey) }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: stargate-api-key
                  optional: true
              {{- else }}
              value: {{ .Values.stargate.apiKey | quote }}
              {{- end }}
            - name: UPLOADS_DIR
              value: /data/uploads
            - name: IPFS_MIRROR_ENABLED
              value: {{ .Values.stargate.ipfs.mirrorEnabled | quote }}
            - name: IPFS_MIRROR_UPLOAD_ENABLED
              value: {{ .Values.stargate.ipfs.mirrorUploadEnabled | quote }}
            - name: IPFS_MIRROR_DOWNLOAD_ENABLED
              value: {{ .Values.stargate.ipfs.mirrorDownloadEnabled | quote }}
            - name: IPFS_API_URL
              value: {{ .Values.stargate.ipfs.apiUrl | quote }}
            - name: IPFS_MIRROR_TOPIC
              value: {{ .Values.stargate.ipfs.mirrorTopic | quote }}
            - name: IPFS_MIRROR_POLL_INTERVAL_SEC
              value: {{ .Values.stargate.ipfs.mirrorPollIntervalSec | quote }}
            - name: IPFS_MIRROR_PUBLISH_INTERVAL_SEC
              value: {{ .Values.stargate.ipfs.mirrorPublishIntervalSec | quote }}
            - name: IPFS_MIRROR_MAX_FILES
              value: {{ .Values.stargate.ipfs.mirrorMaxFiles | quote }}
            - name: IPFS_HTTP_TIMEOUT_SEC
              value: {{ .Values.stargate.ipfs.httpTimeoutSec | quote }}
            - name: IPFS_INGEST_SYNC_ENABLED
              value: {{ .Values.stargate.ipfs.ingestSyncEnabled | quote }}
            - name: IPFS_INGEST_SYNC_INTERVAL_SEC
              value: {{ .Values.stargate.ipfs.ingestSyncIntervalSec | quote }}
            - name: IPFS_INGEST_SYNC_MANIFEST
              value: {{ .Values.stargate.ipfs.ingestSyncManifest | quote }}
            - name: IPFS_INGEST_SYNC_MAX_ENTRIES
              value: {{ .Values.stargate.ipfs.ingestSyncMaxEntries | quote }}
            - name: IPFS_STEGO_TOPIC
              value: {{ .Values.stargate.ipfs.stegoTopic | quote }}
            - name: IPFS_STEGO_ANNOUNCE_ENABLED
              value: {{ .Values.stargate.ipfs.stegoAnnounceEnabled | quote }}
            - name: IPFS_STEGO_SYNC_ENABLED
              value: {{ .Values.stargate.ipfs.stegoSyncEnabled | quote }}
            - name: IPFS_STEGO_SYNC_INTERVAL_SEC
              value: {{ .Values.stargate.ipfs.stegoSyncIntervalSec | quote }}
            - name: STARGATE_STEGO_APPROVAL_ENABLED
              value: {{ .Values.stargate.stego.approvalEnabled | quote }}
            - name: STARGATE_STEGO_METHOD
              value: {{ .Values.stargate.stego.method | quote }}
            - name: STARGATE_STEGO_ISSUER
              value: {{ .Values.stargate.stego.issuer | quote }}
            - name: STARGATE_STEGO_INGEST_TIMEOUT_SEC
              value: {{ .Values.stargate.stego.ingestTimeoutSec | quote }}
            - name: STARGATE_STEGO_INGEST_POLL_SEC
              value: {{ .Values.stargate.stego.ingestPollSec | quote }}
            - name: STARGATE_STEGO_INSCRIBE_TIMEOUT_SEC
              value: {{ .Values.stargate.stego.inscribeTimeoutSec | quote }}
            - name: STARGATE_STEGO_SCAN_TIMEOUT_SEC
              value: {{ .Values.stargate.stego.scanTimeoutSec | quote }}
            - name: MCP_STORE_DRIVER
              value: {{ .Values.mcp.store | quote }}
            - name: MCP_DEFAULT_CLAIM_TTL_HOURS
              value: {{ .Values.mcp.claimTtlHours | quote }}
            - name: MCP_API_KEY
              value: {{ .Values.mcp.apiKey | quote }}
            - name: MCP_SEED_FIXTURES
              value: {{ .Values.mcp.seedFixtures | quote }}
            - name: MCP_ENABLE_INGEST_SYNC
              value: {{ .Values.mcp.enableIngestSync | quote }}
            - name: MCP_ENABLE_FUNDING_SYNC
              value: {{ .Values.mcp.enableFundingSync | quote }}
            - name: MCP_FUNDING_PROVIDER
              value: {{ .Values.mcp.fundingProvider | quote }}
            - name: MCP_FUNDING_API_BASE
              value: {{ .Values.mcp.fundingApiBase | quote }}
            - name: MCP_PG_DSN
              value: {{ .Values.mcp.pgDsn | quote }}
            - name: MCP_INGEST_SYNC_INTERVAL
              value: {{ .Values.mcp.ingestSyncInterval | quote }}
            - name: STARLIGHT_DONATION_ADDRESS
              value: {{ .Values.stargate.donationAddress | quote }}
            {{- if .Values.ca.crt }}
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/ca.crt
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.ca.crt }}
            - name: custom-ca
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
            {{- end }}
          ports:
            - containerPort: {{ .Values.stargate.port }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.stargate.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.stargate.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.stargate.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          resources:
{{ toYaml .Values.resources.stargate | default "{}" | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: stargate-blocks-pvc
        {{- if .Values.ca.crt }}
        - name: custom-ca
          secret:
            secretName: custom-ca
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: stargate-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: stargate-backend
  ports:
    - name: http
      port: 3001
      targetPort: {{ .Values.stargate.port }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stargate-blocks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stargate.blocksStorage }}
  {{- if .Values.stargate.storageClass }}
  storageClassName: {{ .Values.stargate.storageClass | quote }}
  {{- end }}
